<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Maquiagem</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
             
        </style>
    </head>
    <body>
        <h1>Maquiagem</h1>
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Maquiagem</th>

    </tr>
  </thead>
 
        
        <?php
            foreach ($maquiagem as $key => $value) {
                echo "<tr>";
                echo "<td>". $value['id'] . "</td>";
                echo "<td>". $value['nome_pessoa'] . "</td>";
                echo "<td>". $value['nome_maquiagem'] . "</td>";
                echo "</tr>";
            }
        ?>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
    </body>
</html>
