<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  
    <title>Dados do Produto</title>
</head>

<body>

    <div class="container col-12">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                <a class="navbar-brand" href="#"><img src="../img/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                    <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='/perfil/'"
                                        href="#">Perfil</a></div>
                    </div>
                </div>
            </nav>
        </div>

<form action="/dados/" method="post">
        <div class="row mx-auto col-12">
            <div class="col-12 border border-primary">
                <div class="row col-12 rounded-lg">
                    <div class="col-0  py-2 ">

                        <h2> <span class=" label label-default">Informe os dados de seu produto</span></h2>

                    </div>
                </div>
                <div class="row col-12 ">
                    <div class="   col-0 py-2">
            
                        <h3> <span class="label label-default">Endereço de saída</span></h3>
                        <input type="text"class="input-group-text" placeholder="Insira o endereço" name="endereco_saida">
                        <h3> <span class=" label label-default">Endereço de chegada</span></h3>
                        <input type="text" class="input-group-text" placeholder="Insira o endereço" name="endereco_chegada">
                        <h3> <span class="label label-default">Data de saída</span></h3>
                        <div class="container">
                            <div class="row">
                                <div class=" col-10">
                                    <div class="form-group">
                                        <div class="input-group date" id="datetimepicker4" data-target-input="nearest" >
                                            <input type="date" class="input-group-text form-control datetimepicker-input" data-target="#datetimepicker4" name="data">
                                            <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <script type="text/javascript">
                                    $(function () {
                                        $('#datetimepicker4').datetimepicker({
                                            format: 'L'
                                        });
                                    });
                                </script>
                            </div>
                        


                    </div>

                    <div class="mx-auto col-8">
                        <div class="d-block  mx-auto  col-0 pl-0">
                            <button value="Enviar" type="submit" class="btn btn-primary w-200 mt-3 p-2 mx-auto d-block">Confirmar</button>
                        </div>

                    </div>

                </div>

        

            </div>

        </div>
    </form>
    </div> 
    </body> 
      <script src="vendor/jquery/jquery-3.4.1.min.js"></script>
      <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="moment.js"></script>
   </html>
        
  