<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="vendor/fontawesome/css/solid.min.css">
    <link rel="stylesheet" href="style.css">

    <title>Transportadora GMK</title>
</head>

<body>

    <div class="container col-12">
        <div class="row">

            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                    <a class="navbar-brand" href="#"><img src="img/Caixa.png" alt="Box-img"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='index8.html'"
                                        href="#">Perfil</a></div>

                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12">
                <div class="row">
                    <div class="col-12 rodoviaria">

                        <div class="col-12 mx-auto circunferencia">

                        </div>
                        <div class="col-12 botao">
                            <button type="button" class="btn btn-primary col-6" onclick="window.location.href='/cadastro/'">FAÇA JÁ SEU DESPACHO</button>
                        </div>



                    </div>

                </div>



            </div>
        </div>



    </div>

</body>

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>
