<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Logar</title>
</head>

<body>

    <div class="container">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                <a class="navbar-brand" href="#"><img src="../img/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                    <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='index8.html'"
                                        href="#">Perfil</a></div>
                    </div>
                </div>
            </nav>
        </div>

        <?
    if (isset($sucesso)) {
        if ($sucesso == 'fail') {
            echo "Login falhou";
        }
    }
    ?>
<form action="/login/" method="post">
        <div class="row  ml-3">
            <div class="col-12">
                <div class="row col-12 border border-primary rounded-lg ">
                    <div class="col-12  py-2 ">

                        <img class="img-fluid mx-auto d-block" src="../img/icone.png" alt="">
                    </div>
                        <div class="row col-12">
                            <div class=" mx-auto  col-0 py-2">
                                <h2> <span class="label label-default">Informe seu login e senha</h2>
                                <input type="text" id="email" name="email" class="col-12 input-group-text" placeholder="Insira seu email">
                                <input type="password" id="senha" name="senha" class="col-12 input-group-text" placeholder="Insira sua senha">
                            </div>
 
                            <div class="row col-12 py-2">
                                <div class="d-block  mx-auto  col-0 ">
                                    <button type="submit" value="Enviar" class="btn btn-primary">Logar</button>
                                </div>

                            </div>

                       </div>

                    
                </div>
            </div>

        </div>
    </div>
  </form>
        

    </body>
   <script src="vendor/jquery/jquery-3.4.1.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    
    </html>