<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Localizador de Serviço</title>
</head>

<body>

    <div class="container col-12">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                <a class="navbar-brand" href="#"><img src="../img/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                    <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='/perfil/'"
                                        href="#">Perfil</a></div>
                    </div>
                </div>
        </div>
        </nav>

        <?php
    if (isset($sucesso)) {
        if ($sucesso == 'fail') {
            echo  "<script>alert('Serviço inválido nessa região!');</script>";
        }
        if($sucesso == 'true'){
            echo  "<script>alert('Serviço Válido nessa região!');</script>";

        }
        
        
    }
?>

        <form action="/servicos/" method="post">
        <div class="row col-12 mx-auto">
            <div id="login" class="col-12 border border-primary">
                <div class="row ml-5 mt-2">
                    <div>
                        <h2> <span class="label label-default">Localizador de serviço</span></h2>
                    </div>
                    <div class="s-3">
                        <i class="fas fa-truck"></i>
                    </div>
                </div>

                <div class="col-8 mx-auto">
                    <h2> <span class="label label-default">Destino Final:</span></h2>
                    <input class="input-group-text col-12" placeholder="Insira o local" name="cidade" type="text">
                </div>


             


                <div class=" mx-auto col-12 ">
                <button type="submit" value="Enviar" class="w-200 mt-3 p-2 mx-auto d-block btn btn-primary">Localizar</button>
                
                </div>
            </div>

        </div>



    </div>


    </div>
    </div>
    </div>





                </form>
</body>

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="moment.js"></script>

</html>