<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />


    <title>Rastreamento de Produto</title>
</head>

<body>

    <div class="container col-12">
        <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary">
                <a class="navbar-brand" href="#"><img src="../imgsite/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ">
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'" href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'" href="#">Login</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'" href="#">Produtos</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'" href="#">Serviços</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/perfil/'" href="#">Perfil</a></div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
        
        


        <form action="/perfil/" method="post"></form>
        <div class="row border border-primary col-12 mx-auto">

            <div class="col-12">
                <div class="col-8">
                    <h1> Rastreamento de produtos: </h1>
                    <h2><label for="nome">Endereço de saída: </label>
                        <input name="endereco_saida" value="<?php echo $clientes[0]['nome']; ?>" size="20" type="text">
                </div>
                <div class="col-8">
                    <h2><label for="nome">Endereço de chegada: </label>
                        <input name="endereco_chegada" value="<?php echo $clientes[0]['email']; ?>" size="20" type="text">
                </div>
                <div class="col-8">
                    <h2><label for="nome">Data de saída: </label>
                        <input name="data" value="<?php echo $clientes[0]['email']; ?>" size="20" type="date">
                </div>
                <div class="col-8">
                    <h2><label for="nome">Data de chegada: </label>
                        <input name="email" value="<?php echo $clientes[0]['email']; ?>" size="20" type="date">
                </div>

                <div class="col-2"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/perfil/'" href="#">Voltar para o perfil</a>
                </div>

            </div>
            </form>
        </div>
</body>

</html>