<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
    <link rel="stylesheet" href="../style.css">

    <title>Produtos</title>
</head>

<body>

    <div class="container col-12">
        <div class="row">

            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary">
                    <a class="navbar-brand" href="#"><img src="../imgsite/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='/perfil/'"
                                        href="#">Perfil</a></div>

                        </div>
                    </div>
                </nav>
            </div>
        </div>

    <div class = "row col-12 ml-1 mx-auto border border-primary">
        
        <div class = "col-12 ml-1 mx-auto border border-primary">
            <h1 class = "carga_seca">Carga Seca</h1>
            
            <div class = "col-4">
                <img src="../img/Carga Seca.jpg" alt="">
            </div>
            
            <label for="exp_seca" class = "exp_seca">Podemos citar como principais itens desse grupo os seguintes materiais:</label><br>
        
        <div class = "row">
            <div class = "col-12">
                
                <label for="produtos_secos" class = "produtos_secos">
                ° Madeira<br>
                ° Ferragem<br>
                ° Cimento<br>
                ° Material de construção<br>
                ° Produtos de higiene pessoal<br>
                ° Eletrodomésticos<br>
                ° Artigos de vestuários<br>
                ° Peças automotivas<br>
                ° Ferramentas<br>
                </label> 
            
            </div>
        </div>  
        
        </div>


    <div class = "row col-12 ml-1 mx-auto border border-primary">
            <div class = "col-12">
                <h1 class = "carga_refrigerada">Carga Refrigerada</h1>
                
                <div class = " col-4 transporte_refrigerada">
                    <img src="img/Carga Seca.jpg" alt="">
                </div>
                
                <label for="exp_seca" class = "exp_seca">Podemos citar como principais itens desse grupo os seguintes materiais:</label><br>
            
            <div class = "row">
                <div class = "col-12">
                    
                    <label for="produtos_secos" class = "produtos_secos">
                    ° Frutas<br>
                    ° Carnes<br>
                    ° Laticínios<br>
                    ° Medicamentos<br>
                    ° Alimentos congelados em geral<br>
                    </label> 
                
                </div>
            </div>  
            
            </div>
        </div>

        <div class = "row col-12 ml-1 mx-auto border border-primary">
                <div class = "col-12">
                    <h1 class = "carga_refrigerada">Carga Perigosas</h1>
                    
                    <div class = " col-4 transporte_refrigerada">
                        <img src="img/Carga Seca.jpg" alt="">
                    </div>
                    
                    <label for="exp_seca" class = "exp_seca">Podemos citar como principais itens desse grupo os seguintes materiais:</label><br>
                
                <div class = "row">
                    <div class = "col-12">
                        
                        <label for="produtos_secos" class = "produtos_secos">
                        ° Líquidos inflamáveis<br>
                        ° Produtos transportados a altas temperaturas<br>
                        ° Explosivos<br>
                        ° Gases<br>
                        ° Sólidos inflamáveis<br>
                        ° Substâncias oxidantes e peróxidos orgânicos<br>
                        ° Substâncias tóxicas e substâncias infectantes<br>
                        ° Substâncias radioativas<br>
                        ° Corrosivos<br>
                        </label> 
                    
                    </div>
                </div>  
                
                </div>
            </div>   
         
        </div>
</div>

</body>
    <script src="vendor/jquery/jquery-3.4.1.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</html>