<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  
    <title>Perfil</title>
</head>

<body class="col-12">

    <div class="container col-12">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                <a class="navbar-brand" href="#"><img src="../img/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ">
                    <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'"
                                href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'"
                                href="#">Login</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'"
                                href="#">Produtos</a></div>
                        <div class="col-4"> <a
                                class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'"
                                href="#">Serviços</a></div>
                                <div class="col-4"> <a
                                     	class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='index8.html'"
                                        href="#">Perfil</a></div>
                    </div>
                </div>
            </nav>
        </div>



        <div class="row border border-primary col-12 mx-auto">
        
            <div class="col-12">
            <div class="circunferencia2">
                <img src="<?= $img->imagem; ?>" alt="Imagem de perfil">
            </div>
        </div>

        <div class="col-12">
            <div class="col-4">
                <h2><label for="nome">Nome: </label>
                <label for="nome_usuario">...</label>
            </div>
            <div class="col-4">
                <h2><label for="email">E-mail: </label>
                <label for="email_usuario">...</label>
            </div>
            <div class="col-4">
                <h2><label for="cep">Cep: </label>
                <label for="cep_usuario">...</label>   
            </div>
            <div class="col-4" > 
                <h2><label for="cpf">CPF: </label>
                <label for="cpf_usuario">...</label>      
            </div>
            <div class="col-4" >
                <h2><label for="cnpj">CNPJ: </label>
                <label for="cnpj_usuario">...</label>    
            </div>
            <div class="col-3"> <a
                    class="nav-item nav-link border border-dark rounded bg-primary text-white"onclick="window.location.href='index8.html'"
                    href="#">Rastreamento de produto(s)</a>
            </div>

        </div>
        
    </div>
</body>
</html>