<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Cadastro</title>
</head>

<body>

    <div class="container col-12">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded">
                <a class="navbar-brand" href="#"><img src="../img/Caixa.png" alt="Box-img" onclick="window.location.href='/'"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/cadastro/'" href="#">Cadastrar-se</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/login/'" href="#">Login</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/produtos/'" href="#">Produtos</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/servicos/'" href="#">Serviços</a></div>
                        <div class="col-4"> <a class="nav-item nav-link border border-dark rounded bg-primary text-white" onclick="window.location.href='/perfil/'" href="#">Perfil</a></div>
                    </div>
                </div>
        </div>
        </nav>
        <?
    if (isset($sucesso)) {
        if ($sucesso == 'fail') {
            echo "Login falhou";
        }
    }
    ?>

        <form action="/cadastro/" method="post">
            <div class="row col-12 mx-auto">
                <div id="login" class="col-12 border border-primary">
                    <div class="row ml-5 mt-2">
                        <div class="mx-auto row  col-12 ">

                            <div id="imagem" class=" div col-12 ">
                                <img class="img-fluid mx-auto d-block" src="$args['imagem']" alt="">

                            </div>
                        </div>
                        <div class="col-8 mx-auto "><h2> <span class="label label-default">Imagem de perfil</span></h2></div>
                        
                        <div class=" row col-12 mx-auto">
                            <div class=" mx-auto col-12 ">
                                <input class="mx-auto d-block btn btn-primary" type="file" name="imagem">

                            </div>

                        </div>
                        <div class="col-8 mx-auto ">
                            <h2> <span class="label label-default">Nome completo</span></h2>
                            <input class="input-group-text col-12 " placeholder=" Insira seu nome completo" type="text" name="nome" require>
                        </div>
                        <div class="col-8 mx-auto">
                            <h2> <span class="label label-default">Email</span></h2>
                            <input class="input-group-text col-12 " placeholder=" Insira seu login" type="email" name="email" required>
                        </div>
                        <div class="col-8 mx-auto">
                            <h2><span class="label label-default">Senha</span></h2>
                            <input class="input-group-text col-12" placeholder="Senha" type="password" name="senha" required>
                        </div>
                        <div class="col-8 mx-auto">
                           
                            <div class=" mx-auto col-8 ">
                                <button type="submit" value="Enviar" class="btn btn-primary w-200 mt-3 p-2 mx-auto d-block">Cadastrar-se</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </form>

    </div>






</body>

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>